[package]
name = "tv264"
version = "0.1.0"
authors = ["rjeli <eli@rje.li>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
